# domain value below should have a corresponding yml file
# in the /envs folder
domain: 'sharecare' # domain under test
# Set value for test module to true for collection
# Set value for test module to false to skip collection
dom: true
ids: true
class: true
#analytics: false
#dtm: false
seo: false

#domain: 'carldmitch' # domain under test
#dom: true
#ids: true
#class: true
#analytics: false

#